### ISSUE TITLE
How can I change the port from 3000 to something else?

### ISSUE THREAD

**Issue by michelleDeko** [bluesky-social/pds#7]
Hello, I wanted to install Bluesky PDS on my server, but since port 3000 is already getting used for something else important, I tried changing the port from PDS, but I just can't find out how. Is it even possible?

**Comment by devinivy** [comment]
If you're running the docker image, you'll want to map the port `3000` inside the container to whichever port you like on the host machine.  If you're using the compose file, I believe the reason the port used on your host machine is also `3000` is due to this docker setting: https://github.com/bluesky-social/pds/blob/3b955e5a320e5976d8be2bfcdf22f3312fa3e7ad/compose.yaml#L19-L20

There's some more info on how to control this with docker compose here: https://docs.docker.com/compose/networking/

**Comment by michelleDeko** [comment]
> yup, the env var should be PDS_PORT

Thanks that worked. But now I have a problem with creating an invite. I always get the error message "{"error":"AuthenticationRequired","message":"Authentication Required"}#", but I just used the docs for creating a user and changed the hostname and admin_password. Still I get this error

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network, please let us know if there are any issues after this has been pushed. Thank you!
